### ISSUE TITLE
BEM examples and performance

### ISSUE THREAD

**Issue by welleshket** [bem/bem-forum-content-en#11]
1. Any well-known websites use BEM, other than Yandex?

2. In BEM, each block on a page has their own css file, would this increase the page loading time? 

Many thanks!

**Comment by Guria** [comment]
1. A lot of sites all over the world uses BEM naming including even Google (see [WebFundamentals](https://developers.google.com/web/fundamentals/performance/rendering/reduce-the-scope-and-complexity-of-style-calculations?hl=en#use-block-element-modifier) and [MDL](http://www.getmdl.io/faq/index.html#css-naming-conventions)). There are a lot articles on smashing magazine and blog postings about using BEM. See alse, http://getbem.com.

2. No, because all blocks combined into one file in build process before it will be served to browser. Own CSS file for each block needed only in development environment for maintability purposes.

**Comment by welleshket** [comment]
Wow, thank you so much for the fast response!

**Comment by mursya** [comment]
You can also check links here https://en.bem.info/forum/15/

As for companies/sites on BEM: Google, Topcoat by Adobe, Mail.ru, Alfa-lab, a lot of web studios and other sites
